-- Insertion d'observations d'investigation liées aux 50 profils fictifs
-- UID de l'utilisateur : 4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61

-- Note: Les missing_person_id seront récupérés automatiquement via une sous-requête
-- basée sur les noms et prénoms des personnes disparues

INSERT INTO public.investigation_observations (
    missing_person_id, observer_name, observer_phone, observer_email,
    observation_date, observation_time, location_address, location_city, 
    location_state, location_country, location_lat, location_lng,
    description, confidence_level, clothing_description, behavior_description,
    companions, vehicle_info, witness_contact_consent, is_verified,
    verified_by, verified_at, created_by, photos, photo_descriptions
) VALUES 
-- Observations pour Marie Dubois (Paris)
((SELECT id FROM missing_persons WHERE first_name = 'Marie' AND last_name = 'Dubois'), 'Jean Dupont', '0123456789', 'jean.dupont@email.com', '2024-01-16', '14:30:00', '25 Rue de Rivoli', 'Paris', 'Île-de-France', 'France', 48.8566, 2.3522, 'J''ai vu une jeune femme blonde qui ressemblait à la photo dans le métro ligne 1. Elle semblait perdue et regardait sa montre fréquemment.', 'medium', 'Robe noire, chaussures rouges, sac à main noir', 'Semblait anxieuse, regardait sa montre toutes les 2 minutes', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

((SELECT id FROM missing_persons WHERE first_name = 'Marie' AND last_name = 'Dubois'), 'Sophie Martin', '0123456790', 'sophie.martin@email.com', '2024-01-17', '09:15:00', '15 Place de la Concorde', 'Paris', 'Île-de-France', 'France', 48.8656, 2.3212, 'Une femme blonde portant une robe noire était assise sur un banc près de la fontaine. Elle pleurait et avait l''air très triste.', 'high', 'Robe noire, chaussures rouges, sac à main noir', 'Pleurait, semblait très triste et désespérée', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-01-17 10:00:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Pierre Martin (Lyon)
((SELECT id FROM missing_persons WHERE first_name = 'Pierre' AND last_name = 'Martin'), 'Michel Bernard', '0123456791', 'michel.bernard@email.com', '2024-01-21', '11:00:00', '42 Rue de la République', 'Lyon', 'Auvergne-Rhône-Alpes', 'France', 45.7640, 4.8357, 'J''ai vu un homme en costume gris qui ressemblait à la photo dans un café près de la place Bellecour. Il semblait attendre quelqu''un.', 'medium', 'Costume gris, chemise blanche, cravate bleue', 'Semblait attendre quelqu''un, regardait souvent sa montre', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Emma Leroy (Marseille)
((SELECT id FROM missing_persons WHERE first_name = 'Emma' AND last_name = 'Leroy'), 'Catherine Petit', '0123456792', 'catherine.petit@email.com', '2024-01-26', '17:30:00', '8 Rue de la République', 'Marseille', 'Provence-Alpes-Côte d''Azur', 'France', 43.2965, 5.3698, 'Une adolescente brune portant un jean bleu et un pull rose était dans le bus. Elle semblait très jeune et avait l''air perdue.', 'high', 'Jean bleu, pull rose, baskets blanches', 'Semblait perdue, regardait par la fenêtre avec inquiétude', 'Seule', 'Bus ligne 60', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-01-26 18:00:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Antoine Moreau (Toulouse)
((SELECT id FROM missing_persons WHERE first_name = 'Antoine' AND last_name = 'Moreau'), 'Philippe Durand', '0123456793', 'philippe.durand@email.com', '2024-01-29', '10:00:00', '23 Boulevard Saint-Germain', 'Toulouse', 'Occitanie', 'France', 43.6047, 1.4442, 'Un homme en veste de randonnée rouge était dans un magasin de sport. Il achetait des provisions pour la montagne.', 'medium', 'Veste de randonnée rouge, pantalon de trek', 'Semblait préparer une sortie en montagne', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Camille Petit (Nice)
((SELECT id FROM missing_persons WHERE first_name = 'Camille' AND last_name = 'Petit'), 'Isabelle Leroy', '0123456794', 'isabelle.leroy@email.com', '2024-02-02', '19:30:00', '67 Rue de Rivoli', 'Nice', 'Provence-Alpes-Côte d''Azur', 'France', 43.7102, 7.2620, 'Une femme en tailleur noir était dans un restaurant près de la Promenade des Anglais. Elle semblait attendre quelqu''un.', 'medium', 'Tailleur noir, chemisier blanc, escarpins noirs', 'Semblait attendre quelqu''un, regardait souvent sa montre', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Lucas Bernard (Lille)
((SELECT id FROM missing_persons WHERE first_name = 'Lucas' AND last_name = 'Bernard'), 'Nathalie Thomas', '0123456795', 'nathalie.thomas@email.com', '2024-02-06', '23:45:00', '12 Place Bellecour', 'Lille', 'Hauts-de-France', 'France', 50.6292, 3.0573, 'Un jeune homme brun était dans un bar étudiant. Il semblait avoir bu et était très agité.', 'low', 'Jeans, t-shirt blanc, veste en jean', 'Semblait avoir bu, était très agité et parlait fort', 'Avec 2 autres jeunes hommes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Léa Roux (Bordeaux)
((SELECT id FROM missing_persons WHERE first_name = 'Léa' AND last_name = 'Roux'), 'Marc Garcia', '0123456796', 'marc.garcia@email.com', '2024-02-09', '09:00:00', '89 Rue du Commerce', 'Bordeaux', 'Nouvelle-Aquitaine', 'France', 44.8378, -0.5792, 'Une femme brune en pantalon noir était dans une boulangerie. Elle semblait pressée et inquiète.', 'medium', 'Pantalon noir, pull beige, baskets', 'Semblait pressée et inquiète, regardait souvent sa montre', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Maxime Simon (Nantes)
((SELECT id FROM missing_persons WHERE first_name = 'Maxime' AND last_name = 'Simon'), 'Valérie Robert', '0123456797', 'valerie.robert@email.com', '2024-02-13', '21:00:00', '34 Avenue de la Libération', 'Nantes', 'Pays de la Loire', 'France', 47.2184, -1.5536, 'Un homme en costume bleu était dans un hôtel. Il semblait perdu et demandait des renseignements à la réception.', 'high', 'Costume bleu, chemise blanche, chaussures noires', 'Semblait perdu, demandait des renseignements à la réception', 'Seul', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-02-13 21:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Chloé Garcia (Strasbourg)
((SELECT id FROM missing_persons WHERE first_name = 'Chloé' AND last_name = 'Garcia'), 'Laurent Richard', '0123456798', 'laurent.richard@email.com', '2024-02-16', '16:30:00', '56 Rue de la Gare', 'Strasbourg', 'Grand Est', 'France', 48.5734, 7.7521, 'Une jeune femme brune était dans la gare. Elle semblait très stressée et avait l''air de chercher quelqu''un.', 'medium', 'Jeans, pull gris, manteau noir', 'Semblait très stressée, cherchait quelqu''un dans la gare', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Nicolas David (Montpellier)
((SELECT id FROM missing_persons WHERE first_name = 'Nicolas' AND last_name = 'David'), 'Sandrine Leroy', '0123456799', 'sandrine.leroy@email.com', '2024-02-19', '08:00:00', '78 Boulevard des Belges', 'Montpellier', 'Occitanie', 'France', 43.6110, 3.8767, 'Un homme en blouse blanche était dans un café près de l''hôpital. Il semblait très fatigué et avait l''air préoccupé.', 'high', 'Blouse blanche, pantalon de travail, chaussures de sécurité', 'Semblait très fatigué et préoccupé, buvait beaucoup de café', 'Seul', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-02-19 08:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Sarah Lefebvre (Rennes)
((SELECT id FROM missing_persons WHERE first_name = 'Sarah' AND last_name = 'Lefebvre'), 'Céline Moreau', '0123456800', 'celine.moreau@email.com', '2024-02-23', '15:00:00', '45 Rue de la Poste', 'Rennes', 'Bretagne', 'France', 48.1173, -1.6778, 'Une femme blonde en uniforme blanc était dans un parc. Elle semblait très triste et pleurait.', 'medium', 'Uniforme blanc, chaussures de sécurité', 'Semblait très triste, pleurait sur un banc', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Julien Moreau (Reims)
((SELECT id FROM missing_persons WHERE first_name = 'Julien' AND last_name = 'Moreau'), 'Patricia Thomas', '0123456801', 'patricia.thomas@email.com', '2024-02-26', '00:30:00', '23 Place du Marché', 'Reims', 'Grand Est', 'France', 49.2583, 4.0317, 'Un homme en uniforme de cuisine blanc était dans la rue. Il semblait avoir bu et était très agité.', 'low', 'Uniforme de cuisine blanc, chaussures de sécurité', 'Semblait avoir bu, était très agité et parlait fort', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Manon Thomas (Dijon)
((SELECT id FROM missing_persons WHERE first_name = 'Manon' AND last_name = 'Thomas'), 'François Robert', '0123456802', 'francois.robert@email.com', '2024-03-01', '18:00:00', '67 Avenue de la République', 'Dijon', 'Bourgogne-Franche-Comté', 'France', 47.3220, 5.0415, 'Une adolescente brune était dans un centre commercial. Elle semblait perdue et avait l''air de chercher quelqu''un.', 'high', 'Jeans, pull à capuche gris, baskets', 'Semblait perdue, cherchait quelqu''un dans le centre commercial', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-03-01 18:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Alexandre Robert (Angers)
((SELECT id FROM missing_persons WHERE first_name = 'Alexandre' AND last_name = 'Robert'), 'Valérie Lefebvre', '0123456803', 'valerie.lefebvre@email.com', '2024-03-03', '20:00:00', '89 Rue de la Liberté', 'Angers', 'Pays de la Loire', 'France', 47.4784, -0.5632, 'Un homme en costume bleu marine était dans un restaurant. Il semblait attendre quelqu''un et était très nerveux.', 'medium', 'Costume bleu marine, chemise blanche, cravate', 'Semblait attendre quelqu''un, était très nerveux', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Océane Richard (Tours)
((SELECT id FROM missing_persons WHERE first_name = 'Océane' AND last_name = 'Richard'), 'Laurent Petit', '0123456804', 'laurent.petit@email.com', '2024-03-06', '17:00:00', '12 Boulevard des Italiens', 'Tours', 'Centre-Val de Loire', 'France', 47.3941, 0.6848, 'Une femme blonde en tailleur noir était dans un bureau. Elle semblait très stressée et avait l''air de préparer quelque chose.', 'medium', 'Tailleur noir, chemisier blanc, escarpins', 'Semblait très stressée, préparait quelque chose', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Baptiste Petit (Le Havre)
((SELECT id FROM missing_persons WHERE first_name = 'Baptiste' AND last_name = 'Petit'), 'Catherine Durand', '0123456805', 'catherine.durand@email.com', '2024-03-09', '07:00:00', '34 Rue de la Paix', 'Le Havre', 'Normandie', 'France', 49.4944, 0.1079, 'Un homme en veste de marin était sur le port. Il semblait préparer son bateau pour une sortie en mer.', 'high', 'Veste de marin, pantalon de travail, bottes', 'Préparait son bateau pour une sortie en mer', 'Seul', 'Bateau de pêche', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-03-09 07:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Inès Durand (Clermont-Ferrand)
((SELECT id FROM missing_persons WHERE first_name = 'Inès' AND last_name = 'Durand'), 'Philippe Leroy', '0123456806', 'philippe.leroy@email.com', '2024-03-12', '02:00:00', '56 Place de la Victoire', 'Clermont-Ferrand', 'Auvergne-Rhône-Alpes', 'France', 45.7772, 3.0870, 'Une jeune femme brune était dans une boîte de nuit. Elle semblait avoir bu et était très agité.', 'low', 'Robe noire, veste en jean, chaussures noires', 'Semblait avoir bu, était très agité et dansait', 'Avec 2 autres jeunes femmes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Romain Leroy (Amiens)
((SELECT id FROM missing_persons WHERE first_name = 'Romain' AND last_name = 'Leroy'), 'Sandrine Garcia', '0123456807', 'sandrine.garcia@email.com', '2024-03-15', '07:00:00', '78 Avenue du Général de Gaulle', 'Amiens', 'Hauts-de-France', 'France', 49.8943, 2.2958, 'Un homme en uniforme de police était dans un café. Il semblait très fatigué et avait l''air préoccupé.', 'high', 'Uniforme de police, chaussures de sécurité', 'Semblait très fatigué et préoccupé, buvait beaucoup de café', 'Seul', 'Voiture de police', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-03-15 07:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Lola Garcia (Poitiers)
((SELECT id FROM missing_persons WHERE first_name = 'Lola' AND last_name = 'Garcia'), 'Marc Thomas', '0123456808', 'marc.thomas@email.com', '2024-03-18', '15:00:00', '45 Rue de la Mairie', 'Poitiers', 'Nouvelle-Aquitaine', 'France', 46.5802, 0.3404, 'Une jeune femme blonde était dans un parc avec une caméra. Elle semblait faire un reportage.', 'medium', 'Jeans, t-shirt blanc, veste en jean', 'Semblait faire un reportage avec sa caméra', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Quentin Simon (Caen)
((SELECT id FROM missing_persons WHERE first_name = 'Quentin' AND last_name = 'Simon'), 'Marie Robert', '0123456809', 'marie.robert@email.com', '2024-03-21', '19:00:00', '23 Boulevard de la République', 'Caen', 'Normandie', 'France', 49.1829, -0.3707, 'Un homme brun était dans un café avec son ordinateur portable. Il semblait très concentré sur son travail.', 'medium', 'Polo bleu, jean, baskets', 'Semblait très concentré sur son travail sur l''ordinateur', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Clara Bernard (Besançon)
((SELECT id FROM missing_persons WHERE first_name = 'Clara' AND last_name = 'Bernard'), 'Jean Lefebvre', '0123456810', 'jean.lefebvre@email.com', '2024-03-24', '17:00:00', '67 Rue de la Fontaine', 'Besançon', 'Bourgogne-Franche-Comté', 'France', 47.2380, 6.0243, 'Une adolescente blonde était dans un centre commercial. Elle semblait perdue et avait l''air de chercher quelqu''un.', 'high', 'Jeans, pull rose, baskets blanches', 'Semblait perdue, cherchait quelqu''un dans le centre commercial', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-03-24 17:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Théo Lefebvre (Orléans)
((SELECT id FROM missing_persons WHERE first_name = 'Théo' AND last_name = 'Lefebvre'), 'Nathalie Moreau', '0123456811', 'nathalie.moreau@email.com', '2024-03-27', '11:00:00', '34 Place de l''Hôtel de Ville', 'Orléans', 'Centre-Val de Loire', 'France', 47.9029, 1.9093, 'Un homme en combinaison de travail bleue était dans un magasin de bricolage. Il semblait acheter des outils.', 'medium', 'Combinaison de travail bleue, chaussures de sécurité', 'Achetait des outils dans le magasin de bricolage', 'Seul', 'Van de service', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Zoé Moreau (Mulhouse)
((SELECT id FROM missing_persons WHERE first_name = 'Zoé' AND last_name = 'Moreau'), 'Sylvie Thomas', '0123456812', 'sylvie.thomas@email.com', '2024-03-30', '20:00:00', '89 Avenue de la Gare', 'Mulhouse', 'Grand Est', 'France', 47.7508, 7.3359, 'Une jeune femme brune en uniforme de vendeuse était dans un restaurant. Elle semblait très triste.', 'medium', 'Uniforme de vendeuse, chaussures confortables', 'Semblait très triste, mangeait seule', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Enzo Thomas (Nancy)
((SELECT id FROM missing_persons WHERE first_name = 'Enzo' AND last_name = 'Thomas'), 'Martine Robert', '0123456813', 'martine.robert@email.com', '2024-04-02', '18:00:00', '12 Rue de la République', 'Nancy', 'Grand Est', 'France', 48.6921, 6.1844, 'Un jeune homme brun en salopette de travail était dans un garage. Il semblait réparer une voiture.', 'medium', 'Salopette de travail, chaussures de sécurité', 'Réparait une voiture dans le garage', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Léna Robert (Metz)
((SELECT id FROM missing_persons WHERE first_name = 'Léna' AND last_name = 'Robert'), 'Pierre Lefebvre', '0123456814', 'pierre.lefebvre@email.com', '2024-04-05', '18:00:00', '56 Boulevard de la Liberté', 'Metz', 'Grand Est', 'France', 49.1193, 6.1757, 'Une adolescente blonde était dans un parc. Elle semblait très triste et pleurait.', 'high', 'Jeans, pull à capuche bleu, baskets', 'Semblait très triste, pleurait sur un banc', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-04-05 18:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Kylian Richard (Rouen)
((SELECT id FROM missing_persons WHERE first_name = 'Kylian' AND last_name = 'Richard'), 'Catherine Petit', '0123456815', 'catherine.petit@email.com', '2024-04-08', '15:00:00', '23 Place du Marché', 'Rouen', 'Normandie', 'France', 49.4432, 1.0993, 'Un homme brun en uniforme de travail était dans un camion de livraison. Il semblait préparer sa tournée.', 'medium', 'Uniforme de travail, chaussures de sécurité', 'Préparait sa tournée de livraison', 'Seul', 'Camion de livraison', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Maëlle Petit (Le Mans)
((SELECT id FROM missing_persons WHERE first_name = 'Maëlle' AND last_name = 'Petit'), 'François Durand', '0123456816', 'francois.durand@email.com', '2024-04-11', '19:00:00', '78 Rue de la Paix', 'Le Mans', 'Pays de la Loire', 'France', 48.0061, 0.1996, 'Une femme blonde en uniforme de coiffeuse était dans un restaurant. Elle semblait très triste.', 'medium', 'Uniforme de coiffeuse, chaussures confortables', 'Semblait très triste, mangeait seule', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Mathis Durand (Brest)
((SELECT id FROM missing_persons WHERE first_name = 'Mathis' AND last_name = 'Durand'), 'Isabelle Leroy', '0123456817', 'isabelle.leroy@email.com', '2024-04-14', '03:00:00', '45 Avenue de la République', 'Brest', 'Bretagne', 'France', 48.3905, -4.4860, 'Un jeune homme brun était dans une boîte de nuit. Il semblait avoir bu et était très agité.', 'low', 'Jeans, t-shirt blanc, veste en jean', 'Semblait avoir bu, était très agité et dansait', 'Avec 2 autres jeunes hommes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Louise Leroy (Limoges)
((SELECT id FROM missing_persons WHERE first_name = 'Louise' AND last_name = 'Leroy'), 'Philippe Garcia', '0123456818', 'philippe.garcia@email.com', '2024-04-17', '08:00:00', '67 Boulevard des Belges', 'Limoges', 'Nouvelle-Aquitaine', 'France', 45.8336, 1.2611, 'Une femme brune en uniforme blanc était dans un café près de l''hôpital. Elle semblait très fatiguée.', 'high', 'Uniforme blanc, chaussures de sécurité', 'Semblait très fatiguée, buvait beaucoup de café', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-04-17 08:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Nathan Garcia (Perpignan)
((SELECT id FROM missing_persons WHERE first_name = 'Nathan' AND last_name = 'Garcia'), 'Sophie Bernard', '0123456819', 'sophie.bernard@email.com', '2024-04-20', '18:00:00', '34 Rue de la Poste', 'Perpignan', 'Occitanie', 'France', 42.6886, 2.8948, 'Un homme brun en costume marron était dans un restaurant. Il semblait attendre quelqu''un.', 'medium', 'Costume marron, chemise blanche, chaussures noires', 'Semblait attendre quelqu''un, regardait souvent sa montre', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Jade Bernard (Annecy)
((SELECT id FROM missing_persons WHERE first_name = 'Jade' AND last_name = 'Bernard'), 'Michel Moreau', '0123456820', 'michel.moreau@email.com', '2024-04-23', '02:00:00', '89 Place de la Mairie', 'Annecy', 'Auvergne-Rhône-Alpes', 'France', 45.8992, 6.1294, 'Une jeune femme blonde était dans une boîte de nuit. Elle semblait avoir bu et était très agité.', 'low', 'Robe noire, veste en jean, chaussures noires', 'Semblait avoir bu, était très agité et dansait', 'Avec 2 autres jeunes femmes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Hugo Moreau (Avignon)
((SELECT id FROM missing_persons WHERE first_name = 'Hugo' AND last_name = 'Moreau'), 'Céline Thomas', '0123456821', 'celine.thomas@email.com', '2024-04-26', '16:00:00', '12 Boulevard de la République', 'Avignon', 'Provence-Alpes-Côte d''Azur', 'France', 43.9493, 4.8055, 'Un homme brun en polo blanc était dans un parc avec un groupe de touristes. Il semblait faire une visite guidée.', 'medium', 'Polo blanc, pantalon beige, chaussures de marche', 'Faisait une visite guidée avec un groupe de touristes', 'Avec un groupe de 8 touristes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Lilou Thomas (Troyes)
((SELECT id FROM missing_persons WHERE first_name = 'Lilou' AND last_name = 'Thomas'), 'Patricia Robert', '0123456822', 'patricia.robert@email.com', '2024-04-29', '18:00:00', '56 Avenue de la Libération', 'Troyes', 'Grand Est', 'France', 48.2973, 4.0744, 'Une adolescente brune était dans un centre commercial. Elle semblait perdue et avait l''air de chercher quelqu''un.', 'high', 'Jeans, pull à capuche rose, baskets', 'Semblait perdue, cherchait quelqu''un dans le centre commercial', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-04-29 18:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Gabriel Robert (La Rochelle)
((SELECT id FROM missing_persons WHERE first_name = 'Gabriel' AND last_name = 'Robert'), 'Valérie Lefebvre', '0123456823', 'valerie.lefebvre@email.com', '2024-05-02', '09:00:00', '78 Rue de la Gare', 'La Rochelle', 'Nouvelle-Aquitaine', 'France', 46.1603, -1.1511, 'Un homme brun en uniforme de marin était sur le port. Il semblait préparer son bateau pour une sortie en mer.', 'high', 'Uniforme de marin, bottes, gilet de sauvetage', 'Préparait son bateau pour une sortie en mer', 'Seul', 'Bateau de pêche', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-05-02 09:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Eva Richard (Angoulême)
((SELECT id FROM missing_persons WHERE first_name = 'Eva' AND last_name = 'Richard'), 'Laurent Petit', '0123456824', 'laurent.petit@email.com', '2024-05-05', '17:00:00', '23 Place du Marché', 'Angoulême', 'Nouvelle-Aquitaine', 'France', 45.6494, 0.1569, 'Une jeune femme blonde en tailleur noir était dans un bureau. Elle semblait très stressée.', 'medium', 'Tailleur noir, chemisier blanc, escarpins', 'Semblait très stressée, travaillait sur son ordinateur', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Noah Petit (Dunkerque)
((SELECT id FROM missing_persons WHERE first_name = 'Noah' AND last_name = 'Petit'), 'Catherine Durand', '0123456825', 'catherine.durand@email.com', '2024-05-08', '17:00:00', '45 Boulevard des Belges', 'Dunkerque', 'Hauts-de-France', 'France', 51.0344, 2.3768, 'Un homme brun en combinaison de travail était dans un port. Il semblait charger des conteneurs.', 'medium', 'Combinaison de travail, chaussures de sécurité', 'Chargeait des conteneurs dans le port', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Luna Durand (Calais)
((SELECT id FROM missing_persons WHERE first_name = 'Luna' AND last_name = 'Durand'), 'Philippe Leroy', '0123456826', 'philippe.leroy@email.com', '2024-05-11', '17:00:00', '67 Rue de la République', 'Calais', 'Hauts-de-France', 'France', 50.9513, 1.8587, 'Une adolescente brune était dans un centre commercial. Elle semblait perdue et avait l''air de chercher quelqu''un.', 'high', 'Jeans, pull gris, baskets blanches', 'Semblait perdue, cherchait quelqu''un dans le centre commercial', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-05-11 17:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Liam Leroy (Boulogne-sur-Mer)
((SELECT id FROM missing_persons WHERE first_name = 'Liam' AND last_name = 'Leroy'), 'Sandrine Garcia', '0123456827', 'sandrine.garcia@email.com', '2024-05-14', '07:00:00', '34 Avenue de la Gare', 'Boulogne-sur-Mer', 'Hauts-de-France', 'France', 50.7260, 1.6147, 'Un homme brun en veste de marin était sur le port. Il semblait préparer son bateau pour une sortie en mer.', 'high', 'Veste de marin, pantalon de travail, bottes', 'Préparait son bateau pour une sortie en mer', 'Seul', 'Bateau de pêche', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-05-14 07:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Maya Garcia (Bayonne)
((SELECT id FROM missing_persons WHERE first_name = 'Maya' AND last_name = 'Garcia'), 'Marc Thomas', '0123456828', 'marc.thomas@email.com', '2024-05-17', '03:00:00', '12 Rue de la Paix', 'Bayonne', 'Nouvelle-Aquitaine', 'France', 43.4929, -1.4748, 'Une jeune femme brune était dans une boîte de nuit. Elle semblait avoir bu et était très agité.', 'low', 'Robe noire, veste en jean, chaussures noires', 'Semblait avoir bu, était très agité et dansait', 'Avec 2 autres jeunes femmes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Ethan Bernard (Pau)
((SELECT id FROM missing_persons WHERE first_name = 'Ethan' AND last_name = 'Bernard'), 'Nathalie Moreau', '0123456829', 'nathalie.moreau@email.com', '2024-05-20', '19:00:00', '56 Place de la Victoire', 'Pau', 'Nouvelle-Aquitaine', 'France', 43.2951, -0.3708, 'Un homme brun en salopette de travail était dans un garage. Il semblait réparer une voiture.', 'medium', 'Salopette de travail, chaussures de sécurité', 'Réparait une voiture dans le garage', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Aria Moreau (Tarbes)
((SELECT id FROM missing_persons WHERE first_name = 'Aria' AND last_name = 'Moreau'), 'Patricia Thomas', '0123456830', 'patricia.thomas@email.com', '2024-05-23', '18:00:00', '78 Boulevard de la République', 'Tarbes', 'Occitanie', 'France', 43.2338, 0.0781, 'Une adolescente blonde était dans un centre commercial. Elle semblait perdue et avait l''air de chercher quelqu''un.', 'high', 'Jeans, pull à capuche violet, baskets', 'Semblait perdue, cherchait quelqu''un dans le centre commercial', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-05-23 18:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Léo Thomas (Albi)
((SELECT id FROM missing_persons WHERE first_name = 'Léo' AND last_name = 'Thomas'), 'Céline Robert', '0123456831', 'celine.robert@email.com', '2024-05-26', '17:00:00', '23 Avenue de la Gare', 'Albi', 'Occitanie', 'France', 43.9294, 2.1480, 'Un homme brun en costume bleu était dans un bureau. Il semblait très concentré sur son travail.', 'medium', 'Costume bleu, chemise blanche, chaussures noires', 'Semblait très concentré sur son travail sur l''ordinateur', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Nina Robert (Carcassonne)
((SELECT id FROM missing_persons WHERE first_name = 'Nina' AND last_name = 'Robert'), 'Valérie Lefebvre', '0123456832', 'valerie.lefebvre@email.com', '2024-05-29', '16:00:00', '45 Rue de la Poste', 'Carcassonne', 'Occitanie', 'France', 43.2128, 2.3536, 'Une jeune femme brune était dans une bibliothèque. Elle semblait très concentrée sur ses études.', 'medium', 'Jeans, pull gris, manteau noir', 'Semblait très concentrée sur ses études, lisait beaucoup', 'Seule', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Adam Richard (Foix)
((SELECT id FROM missing_persons WHERE first_name = 'Adam' AND last_name = 'Richard'), 'Laurent Petit', '0123456833', 'laurent.petit@email.com', '2024-06-01', '10:00:00', '67 Place du Marché', 'Foix', 'Occitanie', 'France', 42.9606, 1.6074, 'Un homme brun en veste de randonnée était dans un magasin de sport. Il semblait acheter du matériel de montagne.', 'medium', 'Veste de randonnée, pantalon de trek, chaussures de marche', 'Achetait du matériel de montagne dans le magasin de sport', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Zara Petit (Auch)
((SELECT id FROM missing_persons WHERE first_name = 'Zara' AND last_name = 'Petit'), 'Catherine Durand', '0123456834', 'catherine.durand@email.com', '2024-06-04', '02:00:00', '34 Boulevard des Belges', 'Auch', 'Occitanie', 'France', 43.6456, 0.5855, 'Une jeune femme blonde était dans une boîte de nuit. Elle semblait avoir bu et était très agité.', 'low', 'Robe noire, veste en jean, chaussures noires', 'Semblait avoir bu, était très agité et dansait', 'Avec 2 autres jeunes femmes', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Oscar Durand (Montauban)
((SELECT id FROM missing_persons WHERE first_name = 'Oscar' AND last_name = 'Durand'), 'Philippe Leroy', '0123456835', 'philippe.leroy@email.com', '2024-06-07', '18:00:00', '89 Rue de la République', 'Montauban', 'Occitanie', 'France', 44.0176, 1.3542, 'Un homme brun en costume gris était dans un restaurant. Il semblait attendre quelqu''un.', 'medium', 'Costume gris, chemise blanche, chaussures noires', 'Semblait attendre quelqu''un, regardait souvent sa montre', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Iris Leroy (Agen)
((SELECT id FROM missing_persons WHERE first_name = 'Iris' AND last_name = 'Leroy'), 'Sandrine Garcia', '0123456836', 'sandrine.garcia@email.com', '2024-06-10', '15:00:00', '12 Avenue de la Libération', 'Agen', 'Nouvelle-Aquitaine', 'France', 44.2043, 0.6204, 'Une femme brune en uniforme blanc était dans un parc. Elle semblait très fatiguée.', 'high', 'Uniforme blanc, chaussures de sécurité', 'Semblait très fatiguée, se reposait sur un banc', 'Seule', 'Aucun véhicule', true, true, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '2024-06-10 15:30:00+01', '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}'),

-- Observations pour Milo Garcia (Périgueux)
((SELECT id FROM missing_persons WHERE first_name = 'Milo' AND last_name = 'Garcia'), 'Marc Thomas', '0123456837', 'marc.thomas@email.com', '2024-06-13', '00:30:00', '56 Place de l''Hôtel de Ville', 'Périgueux', 'Nouvelle-Aquitaine', 'France', 45.1862, 0.7156, 'Un homme brun en uniforme de cuisine blanc était dans la rue. Il semblait avoir bu et était très agité.', 'low', 'Uniforme de cuisine blanc, chaussures de sécurité', 'Semblait avoir bu, était très agité et parlait fort', 'Seul', 'Aucun véhicule', true, false, null, null, '4cfbe5a6-f0e5-4fc1-a168-7dbd763daf61', '{}', '{}');
